[ARCTIC-1548] Replace log4j 1.2 to reload4j
NetEase/amoro pull request #1549
Opened 2023-06-12 08:32 UTC by XBaith

## Why are the changes needed?

Fix #1548

## Brief change log

## How was this patch tested?
- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

  - Does this pull request introduces a new feature? (no)
  - If yes, how is the feature documented? (not documented)

2023-06-13 01:58 UTC, shidayang commented on pom.xml
> +                <version>${reload4j.version}</version>
what is the difference between ch.qos.reload4j.reload4j and org.slf4j.slf4j-reload4j

2023-06-13 03:16 UTC, zhongqishang commented
AFAIK, Flink connector logging framework depends on log4j2 , And the log dependency will not be packaged into the jar.
I have two confuse:
1. What is the reason for package into jar
2. What is the reason for not upgrade to log4j2

@shidayang @XBaith

2023-06-13 07:39 UTC, zhoujinsong commented
I agree with that we should upgrade the log4j dependency to log4j2 and not package the log dependency into the connector's JAR file.

BTW, does this issue only affect branch 0.4.x, which means the branch master does not have this issue.?

2023-06-13 08:04 UTC, XBaith commented
> BTW, does this issue only affect branch 0.4.x, which means the branch master does not have this issue?

I believe that the branch master is also affected.

2023-06-14 03:21 UTC, shidayang commented
> 
+1 upgrade to log4j2

2023-06-14 06:03 UTC, XBaith commented
> +1 upgrade to log4j2, Could you upgrade log4j to log4j2?
OK, I will upgrade log4j

2023-07-04 01:59 UTC, baiyangtx requested changes
Did you forget to modify the Spark 3.2/3.3 module?

2023-09-26 05:40 UTC, closed without merging