[AMORO-1958][WIP] Support Kubernetes Optimizer
NetEase/amoro pull request #1927
Opened 2023-09-06 14:40 UTC by Kyofin

## Why are the changes needed?

Close  #1958

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2023-09-07 06:39 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/KubernetesOptimizerContainer.java
> +      "- cluster:\n" +
kubeconfig should not appear in code.

2023-09-07 06:39 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/KubernetesOptimizerContainer.java
> +  }
I believe that implementing requestResource directly in K8S mode may be more reasonable. AbstractResourceContainer can even be refactored. 

In my opinion, the abstract methods designed in AbstractResourceContainer are not reasonable at present. those methods are designed to manage the Optimizer through shell commands.

2023-09-07 06:39 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/KubernetesOptimizerContainer.java
> +  }
Is it possible to directly delete the corresponding Pod?

2023-09-07 06:39 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/KubernetesOptimizerContainer.java
> +          client, "registry.cn-hangzhou.aliyuncs.com/udh/amoro-optimizer:0.6.0",String.join(" ",cmd),LOG);
The image address can be passed in through the properties of OptimizerContainer.

2023-09-07 06:39 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/KubernetesOptimizerContainer.java
> +          client, "registry.cn-hangzhou.aliyuncs.com/udh/amoro-optimizer:0.6.0",String.join(" ",cmd),LOG);
Some information related to the K8S cluster can be configured in the K8S Properties, such as the kube_config address and service_account.

2023-09-07 06:39 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/KubernetesOptimizerContainer.java
> +        JOB_MEMORY_PROPERTY));
Can the memory size be limited in the resource request for K8S?

2023-09-07 06:39 UTC, baiyangtx commented on docker/optimizer/localOptimize.sh
> +# regarding copyright ownership.  The ASF licenses this file
Can we copy from the dist module in docker/optimizer/build.sh so that we don't have to maintain an extra copy here?

2023-09-22 07:37 UTC, baiyangtx requested changes

2023-09-22 07:37 UTC, baiyangtx commented on ams/optimizer/pom.xml
> +        <snakeyaml.version>1.33</snakeyaml.version>
Why do we need to modify this version?

2023-09-22 07:37 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/util/K8sUtil.java
> +        .build();
Is using Job a good choice? Should Amoro Optimizer be a persistent computing resource?
Is Deployment or StatefulSet a better choice?

2023-09-22 07:37 UTC, baiyangtx commented on ams/server/pom.xml
> +        <snakeyaml.version>1.33</snakeyaml.version>
Since both Optimizer and AMS modules have this dependency, should their version be included in dependenciesManagements ?

2023-09-22 07:37 UTC, baiyangtx commented on dist/src/main/arctic-bin/conf/config.yaml
> +              client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdmFyOUJIekpPcTl6MmFaQ3VRNUhNTHBCaTBueDEwT3lCRzhKbGFFTUZWSzJSZndDClVjaHdqTzh0OTdDZVN0ZEVBWUpQWUlkanovSGZP
Writing the kube-config file directly in the config is definitely not a good approach. It may be more appropriate to write the config file path.

2023-09-22 07:37 UTC, baiyangtx commented on dist/src/main/arctic-bin/conf/config.yaml
> +              client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdmFyOUJIekpPcTl6MmFaQ3VRNUhNTHBCaTBueDEwT3lCRzhKbGFFTUZWSzJSZndDClVjaHdqTzh0OTdDZVN0ZEVBWUpQWUlkanovSGZP
Do not upload your configuration files to Github. If you want to test conveniently, you can use the AMORO_CONF_DIR environment variable.

2023-09-22 07:37 UTC, baiyangtx commented on docker/optimizer/build.sh
> + docker push  registry.cn-hangzhou.aliyuncs.com/udh/amoro-optimizer:0.6.0
This is not a good docker build.sh. Version, registry, and other information should not be hardcoded in the build.sh file.

Please refer to the `docker/build.sh` file.

2023-09-22 07:37 UTC, baiyangtx commented on docker/optimizer/localOptimize.sh
> +# regarding copyright ownership.  The ASF licenses this file
It seems that this file is exactly the same as `dist/src/main/arctic-bin/bin/localOptimize.sh`. It is suggested to copy this file in build.sh by using the CP command.

2023-09-26 09:33 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/KubernetesOptimizerContainer.java
> +        CPU_PROPERTY);
Is a fixed CPU request value appropriate? Optimizers with more concurrency and those with less concurrency should have different CPU allocations. 
 

I recommend to set the value here to 'cpu-per-parallelism', with a default value of `0` indicating no limitation, and the final CPU request will be `parallelism * cpu-per-parallelism`. 

@zhoujinsong  WDYT?

2023-09-26 09:33 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/KubernetesOptimizerContainer.java
> +        NAMESPACE);
Can we set a default value for Namespace? If AMS is deployed in K8S, we can use the same Namespace as AMS. If AMS is outside the cluster, we can use 'Default' as the default Namespace.

2023-09-26 09:33 UTC, baiyangtx commented on ams/optimizer/src/main/java/com/netease/arctic/optimizer/util/K8sUtil.java
> +        .withNewSpec()
I think we should add common labels to both pod and deployment.

```
amoro/optimizer-group: ${group-name}
amoro/resource-id: ${resource-id}
```

2023-09-26 09:33 UTC, baiyangtx commented on dist/src/main/arctic-bin/conf/config.yaml
> +
Could we set `~/.kube/config` as default value ?

2023-10-12 09:49 UTC, baiyangtx commented
The 'ams/optimizer' module is refactored.  and containers are moved into ams/server module under `com.netease.arctic.server.manager` package.  could you please fix the conflict with master?

2023-10-12 09:50 UTC, baiyangtx reviewed
The `ams/optimizer` module is refactored, and all containers are moved to `ams/server` module under `com.netease.arctic.server.manager` package. 

Could you please fix the conflict with master branch?

2023-11-22 08:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetEase/amoro?pullRequest=1927) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetEase/amoro?pullRequest=1927) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetEase/amoro?pullRequest=1927) it.</sub>

2023-11-22 08:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetEase/amoro?pullRequest=1927) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetEase/amoro?pullRequest=1927) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetEase/amoro?pullRequest=1927) it.</sub>

2024-03-01 06:30 UTC, czy006 commented
I contacted the author and did not follow up. This will be temporarily closed for subsequent re-implementation or further advancement. @zhoujinsong @baiyangtx

2024-03-01 06:30 UTC, closed without merging