[AMORO-1035][Flink] Support customizing mixed-format table source parallelism
NetEase/amoro pull request #1973
Opened 2023-09-13 06:29 UTC by YesOrNo828

## Why are the changes needed?

Support customizing the parallelism of the filestore/logstore source via Flink SQL.

Close #1035 .

## Brief change log

- update flink modules,
- update the filestore and logstore table source

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no) yes
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented) docs

2023-09-13 06:56 UTC, lklhdu approved these changes
LGTM.

2023-09-13 11:32 UTC, huyuanfeng2018 commented
Can you show the rendering of flink webui after the change? As far as I know, Flinksql has not yet supported custom source parallelism. In flinksql, all operators use the parallelism of the previous operator as the current parallelism, so After I customized the source.parallelism , I think the parallelism of subsequent tasks will not run according to the default parallelism of the task.

2023-09-14 14:45 UTC, YesOrNo828 commented
> Can you show the rendering of flink webui after the change? As far as I know, Flinksql has not yet supported custom source parallelism. In flinksql, all operators use the parallelism of the previous operator as the current parallelism, so After I customized the source.parallelism , I think the parallelism of subsequent tasks will not run according to the default parallelism of the task.

@huyuanfeng2018  Thanks for your comment. Actually we could modify the source operater's parallelism through the Table API instead of Flink SQL.  In the `ScanTableSource.getScanRuntimeProvider()` method, we could modify the DataStreamSource's parallelism.

<img width="617" alt="image" src="https://github.com/NetEase/amoro/assets/6017591/e209b8ee-0fbb-421e-a11e-4240ac5bf3c0">

```sql
select * from 
log_data /*+OPTIONS('arctic.read.mode'='log','properties.group.id'='......','parallelism'='5' )*/ --The job parallelism is 10.
```
Specify source parallelism with SQL hint

2023-09-15 02:57 UTC, huyuanfeng2018 commented
> > Can you show the rendering of flink webui after the change? As far as I know, Flinksql has not yet supported custom source parallelism. In flinksql, all operators use the parallelism of the previous operator as the current parallelism, so After I customized the source.parallelism , I think the parallelism of subsequent tasks will not run according to the default parallelism of the task.
> 
> @huyuanfeng2018 Thanks for your comment. Actually we could modify the source operater's parallelism through the Table API. In the `ScanTableSource.getScanRuntimeProvider()` method, we could modify the DataStreamSource's parallelism.
> 
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/6017591/268013157-e209b8ee-0fbb-421e-a11e-4240ac5bf3c0.png">
> ```sql
> select * from 
> log_data /*+OPTIONS('arctic.read.mode'='log','properties.group.id'='......','parallelism'='5' )*/ --The job parallelism is 10.
> ```
> 
> Specify source parallelism with SQL hint

What I am confused about is how the subsequent task changed back to 10 after the scan parallelism was changed? Let me give you an example. From the perspective of flink-table-planner, often a `select` statement in the source table will trigger `Calc`. However, the parallelism in `Calc` is the parallelism of the source Transformation used.:
![image](https://github.com/NetEase/amoro/assets/40817998/0bcc5064-7a0e-4e6f-890d-3b134fe76edb)
I didn’t see this modification in this PR. I would like to know how this is done. In our internal practice, we need to make certain modifications to Flink-table-planner to achieve this effect.

2023-09-15 08:04 UTC, YesOrNo828 commented
> > > Can you show the rendering of flink webui after the change? As far as I know, Flinksql has not yet supported custom source parallelism. In flinksql, all operators use the parallelism of the previous operator as the current parallelism, so After I customized the source.parallelism , I think the parallelism of subsequent tasks will not run according to the default parallelism of the task.
> > 
> > 
> > @huyuanfeng2018 Thanks for your comment. Actually we could modify the source operater's parallelism through the Table API. In the `ScanTableSource.getScanRuntimeProvider()` method, we could modify the DataStreamSource's parallelism.
> > <img alt="image" width="617" src="https://user-images.githubusercontent.com/6017591/268013157-e209b8ee-0fbb-421e-a11e-4240ac5bf3c0.png">
> > ```sql
> > select * from 
> > log_data /*+OPTIONS('arctic.read.mode'='log','properties.group.id'='......','parallelism'='5' )*/ --The job parallelism is 10.
> > ```
> > Specify source parallelism with SQL hint
> 
> What I am confused about is how the subsequent task changed back to 10 after the scan parallelism was changed? Let me give you an example. From the perspective of flink-table-planner, often a `select` statement in the source table will trigger `Calc`. However, the parallelism in `Calc` is the parallelism of the source Transformation used.: ![image](https://user-images.githubusercontent.com/40817998/268159161-0bcc5064-7a0e-4e6f-890d-3b134fe76edb.png) I didn’t see this modification in this PR. I would like to know how this is done. In our internal practice, we need to make certain modifications to Flink-table-planner to achieve this effect.

Because the above example has a window aggregate operator, it can't be chained with the previous source and calc operators, so it will become 10 parallelism, and the source and calc operators are 5 parallelism. This PR does not change the parallelism of the source operator alone, but also the operators in its chain.

2023-09-25 06:15 UTC, huyuanfeng2018 approved these changes
LGTM.

2023-09-27 02:44 UTC, YesOrNo828 commented
Fixed the conflicts after the spotless tool was added to the Flink module.

2023-11-22 08:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetEase/amoro?pullRequest=1973) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetEase/amoro?pullRequest=1973) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetEase/amoro?pullRequest=1973) it.</sub>

2024-01-18 08:17 UTC, czy006 requested changes

2024-01-18 08:17 UTC, czy006 commented on mixed/flink/flink-common/src/main/java/com/netease/arctic/flink/table/descriptors/ArcticValidator.java
> +      ConfigOptions.key("parallelism")
maybe `source.parallelism` name better than `parallelism` ?

2024-01-19 06:23 UTC, czy006 approved these changes

2024-01-19 06:23 UTC, czy006 commented
LGTM

2024-01-22 05:46 UTC, zhoujinsong approved these changes
LGTM.

2024-01-22 05:46 UTC, merged