remove anused config when using external optimizers
NetEase/amoro pull request #2189
Opened 2023-10-25 10:19 UTC by tcodehuber

## Why are the changes needed?

fix:#2188

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2023-10-26 08:04 UTC, wangtaohz requested changes
Thanks for your work! 👍 

I tested the fixed code locally, and verified that even without configuring any containers, we can still choose an external container.
<img width="533" alt="image" src="https://github.com/NetEase/amoro/assets/103108928/bcc3bcdd-bffd-4f71-9f85-13db9700c5a0">


However, I believe there is no need to modify the config file. After modifying it, this PR can be merged.

2023-10-26 14:41 UTC, tcodehuber commented on dist/src/main/arctic-bin/conf/config.yaml
> +#containers:
> This `dist/src/main/arctic-bin/conf/config.yaml` is the default configuration file for users when they run a demo of AMS. I believe it is reasonable to keep localContainer, and there is no need to modify it in this PR.

done.

2023-10-26 14:42 UTC, tcodehuber commented on dist/src/main/arctic-bin/conf/config.yaml
> What is the reason for removing local container from the default config.yaml?

reverted the unnecessary changes

2023-10-27 02:04 UTC, tcodehuber commented
> Thanks for your work! 👍
> 
> I tested the fixed code locally, and verified that even without configuring any containers, we can still choose an external container. <img alt="image" width="533" src="https://user-images.githubusercontent.com/103108928/278257015-bcc3bcdd-bffd-4f71-9f85-13db9700c5a0.png">
> 
> However, I believe there is no need to modify the config file. After modifying it, this PR can be merged.

done

2023-10-27 02:06 UTC, wangtaohz approved these changes
LGTM

2023-10-31 02:12 UTC, merged