[ARCTIC-1863]Support optimizing for partition evolution iceberg table
NetEase/amoro pull request #2303
Opened 2023-11-14 07:16 UTC by shidayang

## Why are the changes needed?
Close #1863 .

## Brief change log
- Modify com.netease.arctic.server.dashboard.MixedAndIcebergTableDescriptor#collectFileInfo to fix dashboard display error
- Fix OptimizingPlaner error when planning partition evolution iceberg table
- Modify IcebergRewriteExecutor to write insert file in new spec and write position delete in old spec

## How was this patch tested?

- [x] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / **no**)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / **not documented**)

2023-11-22 05:40 UTC, wangtaohz commented on ams/server/pom.xml
> +        <dependency>
You should not add this dependency to pom.
BTW, you can configure it in the dependencies of your IDEA project/module.

2023-11-22 05:42 UTC, wangtaohz requested changes

2023-11-22 05:42 UTC, wangtaohz commented on ams/server/src/main/java/com/netease/arctic/server/dashboard/DashboardServer.java
> +    return false;
Unexpected modifications.

2023-11-22 07:14 UTC, wangtaohz reviewed
I have left some comments, PTAL. @shidayang

2023-11-22 07:14 UTC, wangtaohz commented on ams/server/src/main/java/com/netease/arctic/server/dashboard/MixedAndIcebergTableDescriptor.java
> +        Long snapshotId = entry.getSnapshotId();
It should be `long` instead of `Long`.

2023-11-22 08:25 UTC, shidayang commented on ams/server/src/main/java/com/netease/arctic/server/dashboard/PaimonTableDescriptor.java
> +            new PartitionBaseInfo(partitionSt, 0, fileCount, fileSize, lastCommitTime));
yes

2023-11-22 08:30 UTC, shidayang commented on core/src/main/java/org/apache/iceberg/IcebergFindFiles.java
> +public class IcebergFindFiles {
This is not copied from iceberg

2023-11-22 08:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetEase/amoro?pullRequest=2303) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/NetEase/amoro?pullRequest=2303) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: zhoujinsong<br/>:x: shidayang<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetEase/amoro?pullRequest=2303) it.</sub>

2023-11-23 01:51 UTC, shidayang commented on ams/server/src/main/java/com/netease/arctic/server/dashboard/model/PartitionFileBaseInfo.java
> +  private int specId;
This need

2023-11-23 02:53 UTC, wangtaohz commented on core/src/main/java/org/apache/iceberg/IcebergFindFiles.java
> +public class IcebergFindFiles {
We still need to add docs to this class.

2023-11-23 08:07 UTC, wangtaohz approved these changes
LGTM.

There are some conflicts in the front-end static code that need to be resolved.

2023-11-27 07:52 UTC, zhoujinsong reviewed
@shidayang I left some small suggestion.
Please task another look.

2023-11-27 07:52 UTC, zhoujinsong commented on core/src/main/java/org/apache/iceberg/IcebergFindFiles.java
> + * Find iceberg files like {@link org.apache.iceberg.FindFiles} but with more options. Supports scan
Pay attention to the grammar issue, the following description may be more appropriate：
```
Find Iceberg files like {@link org.apache.iceberg.FindFiles} but with more options. Supports scanning
delete files, partition filter and returning SpecId.
```

2023-11-27 07:52 UTC, zhoujinsong commented on ams/server/src/main/java/com/netease/arctic/server/dashboard/MixedAndIcebergTableDescriptor.java
> +        LOG.warn(e.getMessage(), e);
The exception error message will be printed in the trace, so it is not recommended to display the error message again.
```suggestion
        LOG.warn("Failed to close the manifest reader.", e);
```

2023-11-27 07:52 UTC, zhoujinsong commented on ams/server/src/main/java/com/netease/arctic/server/dashboard/MixedAndIcebergTableDescriptor.java
> +    getTableFiles(amoroTable, null, null)
Can the method `getTableFiles` be changed to use an iterator instead of caching all files in a list to reduce memory overhead?

2023-11-27 07:54 UTC, zhoujinsong commented on core/src/main/java/com/netease/arctic/io/writer/GenericIcebergPartitionedFanoutWriter.java
> +public class GenericIcebergPartitionedFanoutWriter extends PartitionedFanoutWriter<Record> {
Add some java doc for the new class.

2023-11-27 07:54 UTC, zhoujinsong commented on core/src/main/java/com/netease/arctic/io/writer/GenericIcebergPartitionedFanoutWriter.java
> +  final PartitionKey partitionKey;
Would it be more appropriate to use the visibility of `private` here?

2023-11-28 02:30 UTC, zhoujinsong approved these changes
LGTM.

2023-11-28 11:32 UTC, merged